### ISSUE TITLE
Presentation Goals (Mar 22)

### ISSUE THREAD

**Issue by george-ma** [F-Ting/Project-Collab#13]
1. Search for a project using front-end regex 

2. New User -> New Project -> Want to be able to click into a project and see project description (ie. contact info)

**Comment by ghost** [comment]
Hey search by reg-ex isn't necessary, i've already created the front end component for it and hooked it up to the backend. We just need to make the endpoint for searching projects by project name and username. 

I'll take care of it today @george-ma @anisha-rohra
