### ISSUE TITLE
Login user when registration is successful

### ISSUE THREAD

**Issue by F-Ting** [F-Ting/Project-Collab#43]
prereq: #33, #40 

Requirement: 
- [] If registration is successful, user should be logged in as well
- [] Upon loggin in, prompt navigation to also change

**Comment by anisha-rohra** [comment]
Think for the sake of time, we should just redirect to login for right now, and expect the user to login - has the added of benefit that during the demo we can easily show that the user we just created can now log in as that user

**Comment by anisha-rohra** [comment]
@F-Ting ^

**Comment by F-Ting** [comment]
Oops, that's fine for now. we don't need this for the Demo
