### ISSUE TITLE
Project Page Changes 

### ISSUE THREAD

**Issue by F-Ting** [F-Ting/Project-Collab#99]
- Add section for task required
- If no photos are added, replace photo with a header saying project name.
- Add email link and use `mailto` link to open default email client for user
- Use icons (facebook, linkedin, email. etc)
- List of users working (associated) with the project. (should have existing API endpoint for this data)

**Comment by bellkelly** [comment]
For the task required field, what type should it be? Just a string so users can write anything they want? Or an association similar to tags so that users choose from predefined roles?

**Comment by F-Ting** [comment]
I was thinking just text description of what the owner wants help on the the project. I've also added one extra thing on here.
